import type { Lang, Bi } from './types';

/** Pick the requested language, falling back to English when a translation is missing. */
export const t = (b: Bi | null | undefined, lang: Lang): string => {
  if (!b) return '';
  const v = lang === 'hi' ? b.hi || b.en : b.en || b.hi;
  return v || '';
};

type S = { en: string; hi: string };
const s = (en: string, hi: string): S => ({ en, hi });

export const UI = {
  appName: s('ExamPulse AI', 'एग्ज़ामपल्स AI'),
  tagline: s('Current affairs, turned into marks.', 'करेंट अफेयर्स, अंकों में बदले।'),

  // nav
  dashboard: s('Dashboard', 'डैशबोर्ड'),
  news: s('Current Affairs', 'करेंट अफेयर्स'),
  quiz: s('Quiz', 'क्विज़'),
  revision: s('Revision', 'रिवीज़न'),
  mistakes: s('Mistake Book', 'गलती पुस्तिका'),
  magazine: s('Magazine', 'मैगज़ीन'),
  search: s('Search', 'खोजें'),
  ask: s('Ask AI', 'AI से पूछें'),
  progress: s('Progress', 'प्रगति'),
  settings: s('Settings', 'सेटिंग्स'),
  stateAffairs: s('State Affairs', 'राज्य विशेष'),

  // dashboard
  goodMorning: s('Good morning', 'सुप्रभात'),
  goodAfternoon: s('Good afternoon', 'नमस्कार'),
  goodEvening: s('Good evening', 'शुभ संध्या'),
  todayIntel: s("Today's Exam Intelligence", 'आज की परीक्षा-दृष्टि'),
  whatToStudy: s('What should I study today?', 'आज मुझे क्या पढ़ना चाहिए?'),
  topNews: s('Top Current Affairs', 'शीर्ष करेंट अफेयर्स'),
  revisionDue: s('Revision Due', 'आज का रिवीज़न'),
  dailyQuiz: s('Daily Quiz', 'दैनिक क्विज़'),
  weakAreas: s('Your Weak Areas', 'आपके कमज़ोर विषय'),
  missed: s('Missed Current Affairs', 'छूटे हुए समाचार'),
  examCountdown: s('Exam Countdown', 'परीक्षा उलटी गिनती'),
  studyProgress: s('Study Progress', 'अध्ययन प्रगति'),
  streak: s('Study Streak', 'निरंतरता'),
  days: s('days', 'दिन'),
  daysLeft: s('days left', 'दिन शेष'),
  setExamDate: s('Set your exam date', 'परीक्षा तिथि निर्धारित करें'),

  // article
  whatHappened: s('What happened', 'क्या हुआ'),
  whyImportant: s('Why it matters', 'यह क्यों महत्वपूर्ण है'),
  examAngle: s('Exam angle', 'परीक्षा की दृष्टि से'),
  background: s('Background', 'पृष्ठभूमि'),
  staticGk: s('Static GK to revise', 'स्थायी सामान्य ज्ञान'),
  organisations: s('Organisations', 'संगठन'),
  terminology: s('Terminology', 'शब्दावली'),
  pyqPattern: s('How this is asked', 'यह कैसे पूछा जाता है'),
  syllabusMap: s('Syllabus mapping', 'पाठ्यक्रम मानचित्रण'),
  practice: s('Practice questions', 'अभ्यास प्रश्न'),
  source: s('Source', 'स्रोत'),
  relevantExams: s('Relevant exams', 'संबंधित परीक्षाएँ'),
  readFull: s('Read at source', 'मूल स्रोत पर पढ़ें'),
  markRevised: s('Mark revised', 'रिवीज़न पूर्ण'),
  bookmark: s('Bookmark', 'सहेजें'),
  bookmarked: s('Saved', 'सहेजा गया'),

  // verification
  verifiedPrimary: s('Primary source', 'प्राथमिक स्रोत'),
  verifiedNews: s('Verified newsroom', 'सत्यापित समाचार-स्रोत'),
  unverified: s('Unverified', 'असत्यापित'),
  unverifiedNote: s(
    'Single unconfirmed report. Verify before quoting it in an answer.',
    'एकल असत्यापित रिपोर्ट। उत्तर में उपयोग से पहले पुष्टि करें।'
  ),
  aiNote: s(
    'Analysis and questions generated by AI from the linked source. Facts are drawn from that source; background is standard reference knowledge. Verify anything you memorise.',
    'विश्लेषण एवं प्रश्न AI द्वारा दिए गए स्रोत से तैयार। तथ्य उसी स्रोत से; पृष्ठभूमि मानक संदर्भ ज्ञान है। याद करने से पहले सत्यापित करें।'
  ),

  // quiz
  startQuiz: s('Start quiz', 'क्विज़ शुरू करें'),
  questions: s('questions', 'प्रश्न'),
  question: s('Question', 'प्रश्न'),
  submit: s('Submit', 'जमा करें'),
  next: s('Next', 'अगला'),
  finish: s('Finish', 'समाप्त'),
  correct: s('Correct', 'सही'),
  incorrect: s('Incorrect', 'गलत'),
  explanation: s('Explanation', 'व्याख्या'),
  accuracy: s('Accuracy', 'सटीकता'),
  timeTaken: s('Time', 'समय'),
  retry: s('Retry', 'पुनः प्रयास'),
  noQuestions: s('No questions available yet.', 'अभी कोई प्रश्न उपलब्ध नहीं।'),
  reviewMistakes: s('Review mistakes', 'गलतियाँ देखें'),
  yourAnswer: s('Your answer', 'आपका उत्तर'),
  rightAnswer: s('Correct answer', 'सही उत्तर'),

  // misc
  all: s('All', 'सभी'),
  high: s('High', 'उच्च'),
  medium: s('Medium', 'मध्यम'),
  low: s('Low', 'निम्न'),
  priority: s('Priority', 'प्राथमिकता'),
  focusMode: s('Serious Aspirant Mode', 'गंभीर अभ्यर्थी मोड'),
  focusModeNote: s(
    'Hides everything below 4-star exam relevance.',
    '4-स्टार से कम परीक्षा-प्रासंगिकता वाली खबरें छिपाएँ।'
  ),
  nothingYet: s('Nothing here yet.', 'अभी यहाँ कुछ नहीं है।'),
  loading: s('Loading…', 'लोड हो रहा है…'),
  today: s('Today', 'आज'),
  yesterday: s('Yesterday', 'कल'),
  articles: s('articles', 'समाचार'),
  viewAll: s('View all', 'सभी देखें'),
  back: s('Back', 'वापस'),
  clearAll: s('Clear all', 'सब हटाएँ'),
  cleared: s('Cleared', 'हल हो गया'),
  timesWrong: s('times wrong', 'बार गलत'),

  // onboarding
  welcome: s('Set up ExamPulse', 'एग्ज़ामपल्स सेट करें'),
  yourName: s('Your name', 'आपका नाम'),
  chooseExams: s('Which exams are you preparing for?', 'आप किन परीक्षाओं की तैयारी कर रहे हैं?'),
  choosePrimary: s('Primary exam', 'मुख्य परीक्षा'),
  chooseState: s('Your state', 'आपका राज्य'),
  examDateQ: s('Exam date (optional)', 'परीक्षा तिथि (वैकल्पिक)'),
  language: s('Language', 'भाषा'),
  getStarted: s('Get started', 'शुरू करें'),
  skip: s('Skip', 'छोड़ें'),

  // ask
  askPlaceholder: s('Ask about any topic — polity, economy, a scheme, a report…', 'किसी भी विषय पर पूछें — राजव्यवस्था, अर्थव्यवस्था, योजना, रिपोर्ट…'),
  askIntro: s(
    'Answers separate current facts from background, and always say what could be asked.',
    'उत्तर में वर्तमान तथ्य और पृष्ठभूमि अलग-अलग, और संभावित प्रश्न भी।'
  ),
  currentFacts: s('Current facts', 'वर्तमान तथ्य'),
  backgroundInfo: s('Background', 'पृष्ठभूमि'),
  examFacts: s('Must-know for exam', 'परीक्षा हेतु आवश्यक'),
  possibleQuestions: s('Possible questions', 'संभावित प्रश्न'),
  askDisclaimer: s(
    'Generated by AI. Cross-check any fact before you memorise it.',
    'AI द्वारा निर्मित। याद करने से पहले तथ्य की पुष्टि करें।'
  ),

  // settings
  exportData: s('Export my data', 'मेरा डेटा निर्यात करें'),
  importData: s('Import data', 'डेटा आयात करें'),
  resetData: s('Reset everything', 'सब कुछ रीसेट करें'),
  dataNote: s(
    'Your progress is stored only in this browser. Export it before switching device or clearing site data.',
    'आपकी प्रगति केवल इसी ब्राउज़र में सुरक्षित है। डिवाइस बदलने से पहले निर्यात करें।'
  ),
  installApp: s('Install app', 'ऐप इंस्टॉल करें'),
  theme: s('Theme', 'थीम'),
  light: s('Light', 'उजला'),
  dark: s('Dark', 'गहरा'),
  system: s('System', 'सिस्टम'),
} as const;

export type UiKey = keyof typeof UI;
export const ui = (key: UiKey, lang: Lang): string => UI[key][lang] || UI[key].en;
